# Generated by Django 5.0.7 on 2025-05-09 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SopaDeLetras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamaño', models.PositiveIntegerField()),
                ('palabras', models.TextField(help_text='Lista de palabras separadas por comas')),
            ],
        ),
    ]
